yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='posts_main'),
    path('group/<slug:slug>/', views.group_posts, name='posts_group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='create_post'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='posts'
    )
    group = models.ForeignKey(
        'Group',
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        'Post',
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='comments',
        verbose_name='Пост',
        help_text='Пост, к которому относится комментарий',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='comments'
    )
    text = models.TextField(
        'Текст комментария',
        help_text='Введите текст комментария'
    )
    created = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )

    class Meta:
        ordering = ['-created']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Подписчик',
        related_name='follower',
        help_text='Пользователь, который подписывается',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='following',
        help_text='Автор, на которого подписываются',
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'

yatube/posts/forms.py
from django import forms

from .models import Group, Post, Comment


class PostForm(forms.ModelForm):
    group = forms.ModelChoiceField(
        queryset=Group.objects,
        help_text='Группа, к которой будет относиться пост',
        label='Group',
        required=False)
    text = forms.CharField(
        widget=forms.Textarea,
        label="Текст поста",
        help_text='Текст нового поста')

    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    text = forms.CharField(
        widget=forms.Textarea,
        label="Текст комментария",
        help_text='Текст нового комментария')

    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.shortcuts import render

from utils import pagination
from .forms import PostForm, CommentForm
from .models import Group, Post, User, Follow


def index(request):
    post_list = Post.objects.select_related('group').all()
    context = pagination(post_list, request)
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    context = {
        'group': group,
    }
    context.update(pagination(post_list, request))
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = Post.objects.filter(author=author)
    posts_count = author.posts.count()
    context = {
        'author': author,
        'posts_count': posts_count,
    }
    if request.user.is_authenticated:
        following = Follow.objects.filter(
            user=request.user,
            author=author
        ).exists()
        context.update({'following': following, })
    context.update(pagination(post_list, request))
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post_obj = get_object_or_404(Post, id=post_id)
    post_count = Post.objects.filter(author=post_obj.author).count()
    current_user = request.user
    form = CommentForm(request.POST or None)
    comments = post_obj.comments.all()
    context = {
        'post_id': post_id,
        'post_obj': post_obj,
        'post_count': post_count,
        'current_user': current_user,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    is_edit = False
    form = PostForm(request.POST or None, files=request.FILES or None,)
    if form.is_valid():
        post_inst = form.save(commit=False)
        post_inst.author = request.user
        post_inst.save()
        return redirect('posts:profile', request.user)
    return render(
        request,
        'posts/create_post.html',
        {'form': form, 'is_edit': is_edit}
    )


@login_required
def post_edit(request, post_id):
    post_inst = get_object_or_404(Post, id=post_id)
    if not request.user == post_inst.author:
        return redirect('posts:post_detail', post_id)
    is_edit = True
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post_inst
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    return render(
        request,
        'posts/create_post.html',
        {'form': form, 'post_id': post_id, 'is_edit': is_edit}
    )


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    followings = Follow.objects.values('author').filter(
        user=request.user)
    post_list = Post.objects.filter(author__in=followings)
    context = pagination(post_list, request)
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        new_following, created = Follow.objects.get_or_create(
            user=request.user,
            author=author
        )
    return redirect('posts:follow_index')


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    if Follow.objects.filter(user=request.user, author=author).exists():
        new_unfollowing = get_object_or_404(
            Follow.objects,
            user=request.user,
            author=author
        )
        new_unfollowing.delete()
    return redirect('posts:follow_index')

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load user_filters %}
    {% block title %}
      {% if is_edit %}
          Редактировать запись
      {% else %}
          Добавить запись
      {% endif %}
    {% endblock %}
    {% block header %}
      {% if is_edit %}
        Редактировать запись
      {% else %}
        Добавить запись
      {% endif %}
    {% endblock %}
    {% block content %}
    <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
                <div class="card-header">
                  {% if is_edit %}
                    Редактировать запись</div>
                  {% else %}
                    Добавить запись
                  {% endif %}
                </div>
              <div class="card-body">
                <form method="post" action="{% if is_edit %}"
                  {% url 'posts:post_edit' post_id %}"
                  {% else %} "{% url 'posts:create_post' %}"
                  {% endif %}" enctype="multipart/form-data">
                  {% csrf_token %}
                  {% for field in form %} 
                    <div class="form-group row my-3">
                      <label for="{{ field.id_for_label }}">
                        {{ field.label }}
                          {% if field.field.required %}
                            <span class="required text-danger">*</span>
                          {% endif %}
                      </label>
                      {{ field|addclass:'form-control' }} 
                        {% if field.help_text %}
                          <small 
                            id="{{ field.id_for_label }}-help"
                            class="form-text text-muted">
                            {{ field.help_text|safe }}
                          </small>
                        {% endif %}
                    </div>
                  {% endfor %}          

                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %}               
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
    </div>
    {% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
  {% block title %}
    Подписки на сайте
  {% endblock %}
  {% block header %}Подписки на сайте{% endblock %}

  {% block content %}
    <div class="container py-5">     
        <h1>Последние обновления подписок на сайте</h1>
        {% include 'includes/switcher.html' %}
          {% for post in page_obj %}
            <article>
              <ul>
                <li>
                  Автор: {{ post.author.get_full_name }} <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
                </li>
                <li>
                  Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
              </ul>
              {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
              {% endthumbnail %}
              <p>{{ post.text }}</p>
              <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
            </article>
              {% if post.group %}
                <a href="{% url 'posts:posts_group_list' post.group.slug %}">все записи группы</a>
              {% else %}
                <a href="{% url 'posts:posts_main' %}">все записи группы</a>
              {% endif %}
              {% if not forloop.last %}<hr>{% endif %}
          {% endfor %}
          {% include 'includes/paginator.html' %}  

    </div>  
  {% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
  {% block title %}
    Записи сообщества {{ group.title }}
  {% endblock %}    
  {% block content %}
  <div class="container py-5">     
    <h1>{{ group.title }}</h1>
    <p>
      {{ group.description }}
    </p>

        {% for post in page_obj %}
        <article>
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }} <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}          
          <p>{{ post.text }}</p>
          <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
        </article>
          {% if post.group %}
            <a href="{% url 'posts:posts_group_list' post.group.slug %}">все записи группы</a>
          {% else %}
            <a href="{% url 'posts:posts_main' %}">все записи группы</a>
          {% endif %}
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
    
    {% include 'includes/paginator.html' %} 
  </div>  
  {% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load cache %}
{% load thumbnail %}
  {% block title %}
    Последние обновления на сайте
  {% endblock %}
  {% block header %}Последние обновления на сайте{% endblock %}

  {% block content %}
  {% cache 20 index_page with page_obj %}
    <div class="container py-5">     
        <h1>Последние обновления на сайте</h1>
        {% include 'includes/switcher.html' %}

          {% for post in page_obj %}
            <article>
              <ul>
                <li>
                  Автор: {{ post.author.get_full_name }} <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
                </li>
                <li>
                  Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
              </ul>
              {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
              {% endthumbnail %}
              <p>{{ post.text|safe }}</p>
              <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
            </article>
              {% if post.group %}
                <a href="{% url 'posts:posts_group_list' post.group.slug %}">все записи группы</a>
              {% else %}
                <a href="{% url 'posts:posts_main' %}">все записи группы</a>
              {% endif %}
              {% if not forloop.last %}<hr>{% endif %}
          {% endfor %}

          {% include 'includes/paginator.html' %}  

    </div>  
  {% endcache %}
  {% endblock %}
  

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
  {% block title %}
  Пост  {{ post_obj.text|truncatechars:30 }}
  {% endblock %}
  {% block header %}Подробная информация о публикации{% endblock %}
  {% block content %}
  <div class="container py-5"> 
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post_obj.pub_date|date:"d E Y" }} 
        </li>
          <li class="list-group-item">
            {% if post_obj.group %}
              Группа: {{ post_obj.group }}
              <a href="{% url 'posts:posts_group_list' post_obj.group.slug %}">все записи группы</a>
            {% else %}
              Группа:
              <a href="{% url 'posts:posts_main' %}">все записи группы</a>
            {% endif %}
          </li>
          <li class="list-group-item">
            Автор: {{ post_obj.author.get_full_name }}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span >{{ post_count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post_obj.author %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post_obj.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
        {{ post_obj.text|safe }} 
      </p>
      {% if post_obj.author == current_user %}
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post_obj.id %}">
          редактировать пост
        </a>
      {% else %}
        <a class="btn btn-danger" href="">редактирование поста запрещено</a>      
      {% endif %}
      {% include 'includes/add_comments.html' %}
    </article>
  </div>  
  </div> 
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
  {% block title %}
    Профайл пользователя {{ full_name }}
  {% endblock %}
  {% block header %}Профайл пользователя{% endblock %}
  {% block content %}
    <div class="container py-5">     
        <h1>Все посты пользователя {{ author }}</h1>
        <h3>Всего постов: {{ posts_count }}</h3>
        {% include 'includes/funf_button.html' %}
          {% for post in page_obj %}
          <article>
            <ul>
              <li>
                Автор: {{ post.author.get_full_name }} <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
            </ul>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}            
            <p>{{ post.text|safe }}</p>
            <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
        </article>
            {% if post.group %}
                <a href="{% url 'posts:posts_group_list' post.group.slug %}">все записи группы</a>
              {% else %}
                <a href="{% url 'posts:posts_main' %}">все записи группы</a>
              {% endif %}
              {% if not forloop.last %}<hr>{% endif %}
          {% endfor %}
        {% include 'includes/paginator.html' %}  
    </div>  
  {% endblock %}

yatube/templates/posts/switcher.html
{% if user.is_authenticated %}
  <div class="row my-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a 
          class="nav-link {% if index %}active{% endif %}"
          href="{% url 'posts:index' %}"
        >
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a 
           class="nav-link {% if follow %}active{% endif %}"
           href="{% url 'posts:follow_index' %}"
        >
          Избранные авторы
        </a>
      </li>
    </ul>
  </div>
{% endif %}